# Constants
#CLASS_WEIGHTS = np.array([1.5,0.7,0.5], dtype='float32')
CLASSES = ["sphere", "can", "bottle"]
NUM_CLASSES = len(CLASSES)
BOUNDING_BOX_ATTRIBUTES = 5  # 4 for x,y,w,h and 1 for confidence

GRID_DIM = 7
NUM_BOXES = 2
NUM_DENSE_NODES = (GRID_DIM*GRID_DIM*NUM_BOXES*(BOUNDING_BOX_ATTRIBUTES+NUM_CLASSES))
OUTPUT_SHAPE = (GRID_DIM, GRID_DIM, NUM_BOXES, BOUNDING_BOX_ATTRIBUTES+NUM_CLASSES)

BATCH_SIZE = 8
INPUT_SIZE = 448

WEIGHT_PATH = "tiny_yolov1_weights.h5"

NO_OBJECT_SCALE = 1.
OBJECT_SCALE = 5.0
COORD_SCALE = 2.5
CLASS_SCALE = 1.0
